services:
  backend:
    build:
      context: backend/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/src:/app/src
      - ./backend/logs:/app/logs
    env_file:
      - ./backend/.env
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/api/v1/health" ]
      interval: 600s
      timeout: 10s
      retries: 3
